// Code generated by mockery v1.1.2. DO NOT EDIT.

package main

import mock "github.com/stretchr/testify/mock"

// MockFailer is an autogenerated mock type for the Failer type
type MockFailer struct {
	mock.Mock
}

// Dispatch provides a mock function with given fields: q
func (_m *MockFailer) Dispatch(q Query) {
	_m.Called(q)
}

// Fail provides a mock function with given fields: q
func (_m *MockFailer) Fail(q Query) {
	_m.Called(q)
}

// Start provides a mock function with given fields:
func (_m *MockFailer) Start() {
	_m.Called()
}
