// Code generated by mockery v1.1.2. DO NOT EDIT.

package main

import mock "github.com/stretchr/testify/mock"

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

// Dispatch provides a mock function with given fields: q
func (_m *MockQuerier) Dispatch(q Query) {
	_m.Called(q)
}

// Fail provides a mock function with given fields: q
func (_m *MockQuerier) Fail(q Query) {
	_m.Called(q)
}

// Query provides a mock function with given fields: q
func (_m *MockQuerier) Query(q Query) (Query, error) {
	ret := _m.Called(q)

	var r0 Query
	if rf, ok := ret.Get(0).(func(Query) Query); ok {
		r0 = rf(q)
	} else {
		r0 = ret.Get(0).(Query)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(Query) error); ok {
		r1 = rf(q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Start provides a mock function with given fields:
func (_m *MockQuerier) Start() {
	_m.Called()
}
