// Code generated by mockery v1.1.2. DO NOT EDIT.

package main

import mock "github.com/stretchr/testify/mock"

// MockConnector is an autogenerated mock type for the Connector type
type MockConnector struct {
	mock.Mock
}

// AddUpstream provides a mock function with given fields: u
func (_m *MockConnector) AddUpstream(u *Upstream) {
	_m.Called(u)
}

// AssignConnection provides a mock function with given fields: q
func (_m *MockConnector) AssignConnection(q Query) Query {
	ret := _m.Called(q)

	var r0 Query
	if rf, ok := ret.Get(0).(func(Query) Query); ok {
		r0 = rf(q)
	} else {
		r0 = ret.Get(0).(Query)
	}

	return r0
}

// Dispatch provides a mock function with given fields: q
func (_m *MockConnector) Dispatch(q Query) {
	_m.Called(q)
}

// Fail provides a mock function with given fields: q
func (_m *MockConnector) Fail(q Query) {
	_m.Called(q)
}

// Start provides a mock function with given fields:
func (_m *MockConnector) Start() {
	_m.Called()
}
