// Code generated by mockery v1.1.2. DO NOT EDIT.

package main

import mock "github.com/stretchr/testify/mock"

// MockCachedConn is an autogenerated mock type for the CachedConn type
type MockCachedConn struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *MockCachedConn) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
