// Code generated by mockery v1.1.2. DO NOT EDIT.

package main

import mock "github.com/stretchr/testify/mock"

// MockQueryHandlerWorker is an autogenerated mock type for the QueryHandlerWorker type
type MockQueryHandlerWorker struct {
	mock.Mock
}

// Dispatch provides a mock function with given fields: q
func (_m *MockQueryHandlerWorker) Dispatch(q Query) {
	_m.Called(q)
}

// Fail provides a mock function with given fields: q
func (_m *MockQueryHandlerWorker) Fail(q Query) {
	_m.Called(q)
}

// Start provides a mock function with given fields:
func (_m *MockQueryHandlerWorker) Start() {
	_m.Called()
}
