// Code generated by mockery v1.1.2. DO NOT EDIT.

package main

import (
	dns "github.com/miekg/dns"
	mock "github.com/stretchr/testify/mock"
)

// MockResponseWriter is an autogenerated mock type for the ResponseWriter type
type MockResponseWriter struct {
	mock.Mock
}

// WriteMsg provides a mock function with given fields: _a0
func (_m *MockResponseWriter) WriteMsg(_a0 *dns.Msg) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*dns.Msg) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
