// Code generated by mockery v1.1.2. DO NOT EDIT.

package main

import mock "github.com/stretchr/testify/mock"

// MockPipelineServerWorker is an autogenerated mock type for the PipelineServerWorker type
type MockPipelineServerWorker struct {
	mock.Mock
}

// Dispatch provides a mock function with given fields: q
func (_m *MockPipelineServerWorker) Dispatch(q Query) {
	_m.Called(q)
}

// Fail provides a mock function with given fields: q
func (_m *MockPipelineServerWorker) Fail(q Query) {
	_m.Called(q)
}

// Start provides a mock function with given fields:
func (_m *MockPipelineServerWorker) Start() {
	_m.Called()
}
