// Code generated by mockery v1.1.2. DO NOT EDIT.

package main

import mock "github.com/stretchr/testify/mock"

// MockTrashMan is an autogenerated mock type for the TrashMan type
type MockTrashMan struct {
	mock.Mock
}

// AddResponse provides a mock function with given fields: r
func (_m *MockTrashMan) AddResponse(r Response) {
	_m.Called(r)
}

// Evict provides a mock function with given fields: r
func (_m *MockTrashMan) Evict(r Response) {
	_m.Called(r)
}

// FlushResponses provides a mock function with given fields:
func (_m *MockTrashMan) FlushResponses() {
	_m.Called()
}

// Pause provides a mock function with given fields:
func (_m *MockTrashMan) Pause() {
	_m.Called()
}

// Paused provides a mock function with given fields:
func (_m *MockTrashMan) Paused() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ResponsesQueued provides a mock function with given fields:
func (_m *MockTrashMan) ResponsesQueued() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Start provides a mock function with given fields: r
func (_m *MockTrashMan) Start(r *RecordCache) {
	_m.Called(r)
}

// Stop provides a mock function with given fields:
func (_m *MockTrashMan) Stop() {
	_m.Called()
}

// Unpause provides a mock function with given fields:
func (_m *MockTrashMan) Unpause() {
	_m.Called()
}
