// Code generated by mockery v1.1.2. DO NOT EDIT.

package main

import mock "github.com/stretchr/testify/mock"

// MockJanitor is an autogenerated mock type for the Janitor type
type MockJanitor struct {
	mock.Mock
}

// Start provides a mock function with given fields: r
func (_m *MockJanitor) Start(r *RecordCache) {
	_m.Called(r)
}

// Stop provides a mock function with given fields:
func (_m *MockJanitor) Stop() {
	_m.Called()
}
