// Code generated by mockery v1.1.2. DO NOT EDIT.

package main

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockQueryDurationTimer is an autogenerated mock type for the QueryDurationTimer type
type MockQueryDurationTimer struct {
	mock.Mock
}

// ObserveDuration provides a mock function with given fields:
func (_m *MockQueryDurationTimer) ObserveDuration() time.Duration {
	ret := _m.Called()

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}
