// Code generated by mockery v1.1.2. DO NOT EDIT.

package main

import (
	dns "github.com/miekg/dns"
	mock "github.com/stretchr/testify/mock"
)

// MockQueryHandler is an autogenerated mock type for the QueryHandler type
type MockQueryHandler struct {
	mock.Mock
}

// Dispatch provides a mock function with given fields: q
func (_m *MockQueryHandler) Dispatch(q Query) {
	_m.Called(q)
}

// Fail provides a mock function with given fields: q
func (_m *MockQueryHandler) Fail(q Query) {
	_m.Called(q)
}

// ServeDNS provides a mock function with given fields: w, r
func (_m *MockQueryHandler) ServeDNS(w dns.ResponseWriter, r *dns.Msg) {
	_m.Called(w, r)
}

// Start provides a mock function with given fields:
func (_m *MockQueryHandler) Start() {
	_m.Called()
}
