// Code generated by mockery v1.1.2. DO NOT EDIT.

package main

import mock "github.com/stretchr/testify/mock"

// MockCacher is an autogenerated mock type for the Cacher type
type MockCacher struct {
	mock.Mock
}

// Dispatch provides a mock function with given fields: q
func (_m *MockCacher) Dispatch(q Query) {
	_m.Called(q)
}

// Fail provides a mock function with given fields: q
func (_m *MockCacher) Fail(q Query) {
	_m.Called(q)
}

// Start provides a mock function with given fields:
func (_m *MockCacher) Start() {
	_m.Called()
}
